# Generated by Django 5.2.4 on 2025-08-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_master_service_order_review_master_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
